FROM almalinux
ADD https://raw.githubusercontent.com/trussworks/terraform-aws-s3-private-bucket/main/main.tf /tmp/
ADD https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.73/bin/embed/apache-tomcat-9.0.73-embed.tar.gz /tmp/
